services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: dockerfile
    image: hw/nginx
    # проброс портов
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      php:
        condition: service_started
    networks:
      - default_network


  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - TELEGRAM_ADMIN_ID=${TELEGRAM_ADMIN_ID}
      - DATABASE_URL=pgsql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - default_network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - default_network

#  worker:
#    build:
#      context: ./docker/php
#    volumes:
#      - .:/var/www/html
#    depends_on:
#      - rabbitmq
#      - postgres
#    command: php bin/worker notification:process
#    environment:
#      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
#      - DATABASE_URL=pgsql://library:library@postgres:5432/library
#      - RABBITMQ_HOST=rabbitmq
#      - RABBITMQ_PORT=5672
#      - RABBITMQ_USER=guest
#      - RABBITMQ_PASSWORD=guest
#    restart: unless-stopped
#    networks:
#      - default_network

####> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-16}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#      POSTGRES_USER: ${POSTGRES_USER:-app}
#    healthcheck:
#      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
#      timeout: 5s
#      retries: 5
#      start_period: 60s
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
#      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      # - ./docker/db/data:/var/lib/postgresql/data:rw
####< doctrine/doctrine-bundle ###

volumes:
  postgres_data:

networks:
  default_network:
    driver: bridge
