name: Deploy to VPS with Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Navigate to your application directory on the VPS
          cd /home/library
          # Pull the latest code (if not using a container registry)
          git pull origin master
          docker compose down
          # Stop and remove old containers, pull new images, and start new containers
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d --build --wait
          # Optional: Prune old images
          docker image prune -f

          docker compose -f docker-compose.prod.yml exec --user root php composer install --no-interaction
          docker compose -f docker-compose.prod.yml exec --user root php php bin/console doctrine:migrations:migrate --no-interaction
          docker compose -f docker-compose.prod.yml exec -d --user root php php bin/console nutgram:run
          #Надо дождаться запуска rabbitmq?
          sleep(10)
          docker compose -f docker-compose.prod.yml exec --user root php bin/console messenger:setup-transports
          docker compose -f docker-compose.prod.yml exec -d --user root php php bin/console messenger:consume async

